### ISSUE TITLE
how to get data refereed on page 133

### ISSUE THREAD

**Issue by Sandy4321** [PacktPublishing/Mastering-Machine-Learning-for-Penetration-Testing#1]
page 133
Intrusion Detection Evaluation Dataset (CICIDS2017): http:/ / www. unb. ca/
cic/ datasets/ ids- 2017. html

there is no downloadable link

**Comment by chihebchebbi** [comment]
The CICIDS2017 dataset consists of labeled network flows, including full packet payloads in pcap format, the corresponding profiles and the labeled flows (GeneratedLabelledFlows.zip) and CSV files for machine and deep learning purpose (MachineLearningCSV.zip) are publicly available for researchers. For more information and ask for the dataset contact cic@unb.ca

**Comment by RichardPhilipsRoy** [comment]
the link provided in chapter 2 page 55 isn't working
https://labs-repos.iit.demokritos.gr/skel/i-config/:

**Comment by RichardPhilipsRoy** [comment]
Help Chapter 2 page 59
I'm getting this error

Traceback (most recent call last):
  File "nlp.py", line 19, in <module>
    in emails]
NameError: name 'emails' is not defined

I've added a new line to existing code defining emails = '/mnt/c/Windows/System32/spam-project/enron1/emails/'

and now I'm getting this error 

Traceback (most recent call last):
  File "nlp.py", line 20, in <module>
    in emails]
ValueError: need more than 1 value to unpack

**Comment by techsachinkumar** [comment]
Hi @Sandy4321 

If you follow the link, at the end of the page you should find an option to download the dataset.
Its available i just checked. 
Let us know incase of any other query.

Regards,

**Comment by Sandy4321** [comment]
the link provided in chapter 2 page 55 isn't working
https://labs-repos.iit.demokritos.gr/skel/i-config/:
as written by 

  | richard philips roy
-- | --

**Comment by Sandy4321** [comment]
2 links

ICRAplus & FilterXRead about the release of ICRAplus and FilterXDownload and try ICRAplus and FilterX
--

from 
https://labs-repos.iit.demokritos.gr/skel/i-config/
give error
Not Found
The requested URL /_en/icraplus/ was not found on this server.

Apache/2.2.3 (Red Hat) Server at www.icra.org Port 80
![image](https://user-images.githubusercontent.com/11426119/50837673-3594a900-132a-11e9-8d26-dd47abe692d3.png)
