### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by unresolvedhost** [PacktPublishing/Mastering-Machine-Learning-for-Penetration-Testing#2]
when I compiled code from SpamDetection_NLTK.py
I've got an error 

Traceback (most recent call last):
  File "SpamDetection_NLTK.py", line 20, in <module>
    in emails]
NameError: name 'emails' is not defined

So added the code lines of Shuffle.py to SpamDetection_NLTK.py
and replaced emails in Features with emails_list
and now I'm getting this error, please help

Traceback (most recent call last):
  File "SpamDetection_NLTK.py", line 30, in <module>
    in emails_list]

**Comment by bakeunbin** [comment]
For the part,
`features = [(features_extraction (email, 'bow'), label) for (email, label) in emails]`
You need to create your own `emails` variable. 

I am not going to give the easy answer, but if you know how to write python script, then you realize that `emails` should be a list which contains tuples - or pairs - of email contents and the label (whether ham or spam).

e.g., `emails = [('Subject: ...', 'ham'), ('Subject: ...', 'spam'), ...]` and so on.
