### ISSUE TITLE
zip files from CICFlowMeter cannot be opened on Windows OS

### ISSUE THREAD

**Issue by Sandy4321** [PacktPublishing/Mastering-Machine-Learning-for-Penetration-Testing#4]
zip files from 

https://www.unb.ca/cic/research/applications.html#CICFlowMeter

cannot be opened on Windows OS

**Comment by komalkarne** [comment]
Can you highlight the instance from where this link is picked from the book? There are links in the book that redirects to the CIC datasets but not the one which is mentioned above.

**Comment by Sandy4321** [comment]
I can not find them neither
may you share working links from book?
